version: '2.29.0'

services:
  db:
    build:
      context: ./pessoa
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pessoa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backendPessoa
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pessoa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  frontend:
    build:
      context: ./front-endpessoa-main
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
